ethereum_rpc = "https://0xrpc.io/hoodi"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.blacklisted_operator]
path = "out/BlacklistedOperatorTrap.sol/BlacklistedOperatorTrap.json"
response_contract = "0x28077e880b834eCbB67D674E65C5bDE769C0e935"  # deployed Responder
response_function = "respondToBlacklist(address,bool)"
block_sample_size = 5
cooldown_period_blocks = 0
private_trap = true
whitelist = ["0x1cfbC344406468d64fa0997380395ebD0c83CCaE"] # your operator
